apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app-deployment
  labels:
    app: book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: book-app
          image: oleh88895/book-app
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  key: env
                  name: db-config
---
apiVersion: v1
kind: Service
metadata:
  name: book-app-service
spec:
  type: NodePort
  selector:
    app: book-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001

# https://minikube.sigs.k8s.io/docs/handbook/accessing/ access locally app - Using minikube service with tunnel
